### ISSUE TITLE
Feature request: Fetch team's photos from intranet

### ISSUE THREAD

**Issue by Shwetakale** [joshsoftware/website#87]
@SagareGanesh has suggested to fetch team's photos from Josh Intranet so they don't need to send PR when they want to update it. Good idea @SagareGanesh.

To add in the above I think we can also take all data (Team's information) from Intranet by adding one API to intranet so nothing will be hard coded in git repository but if we want to do this then details should be approved by HR. 

And one more concern over here is do we want dependency of intranet API in  website? 
@sethu @gautamrege Thoughts?

**Comment by Ashviniv** [comment]
@sethu @gautamrege  @Shwetakale  I am adding the APIs to get team members data from Intranet to the website.I noticed couple of things: 

1. There is a mismatch between the current static team data hash on the website and database field names on the intranet.

2. Following fields are missing for the team members on the intranet:
    1. Title (Designation)
    2. Description
    3. linkedin_url
    4. facebook_url 

Shall we add these fields and also add view changes as per the Intranet API response field names?

**Comment by Shwetakale** [comment]
@Ashviniv yes I think we shall add. 

@Ashviniv  @sethu  Also I think we also need to add one more boolean field ```visible_on_website``` as we don't want show profiles of interns on website and vice versa. This should be editable by admin / HR only.

**Comment by Shwetakale** [comment]
Deployed this feature
