### ISSUE TITLE
More Info in  Readme.md File

### ISSUE THREAD

**Issue by jitendra3109** [joshsoftware/website#89]
I just landed here  seeing readme.md  file there is nothing about the website and there is not also link to see website . So how to get about overview for a contribution way?

**Comment by gautamrege** [comment]
The website info :). codecuriosity.org

- Gautam
Sent from my iPhone

www.joshsoftware.com

**Comment by jitendra3109** [comment]
@gautamrege Okay, Thanks. You can  link this website also here. So nobody confused. Actually, I was also confused.Can I do this? Little bit Intro page and also provide Link here.
